### ISSUE TITLE
docker-compose容器启动报错退出

### ISSUE THREAD

**Issue by Clov614** [danni-cool/wechatbotKit-py-http#15]
![image](https://github.com/user-attachments/assets/2294a536-72fb-43ef-a7f9-6884b60e5504)

docker-compose如下：

```
version: '3.5'

services:
  desktop:
    image: dannicool/wechatbot-provider-windows:wc-3935
    container_name: DESKTOP
    ports:
      - "13389:3389"
      - "10086:10086"  # RPC 推消息端口
      - "10087:10087"  # RPC 收消息端口
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    volumes:
      - ./wechat/program:/root/.wine/drive_c/Program Files/Tencent/WeChat  # 程序文件挂载
      - ./wechat/user_dat:/root/.wine/drive_c/users/root/AppData/Roaming/Tencent/WeChat  # 用户数据挂载
    restart: unless-stopped # 可选，根据需要配置重启策略
```

**Comment by jiyi** [comment]
添加`stdin_open: true` 和 `tty: true`
 
```
services:
  wechatbot:
    image: dannicool/wechatbot-provider-windows:wc-3935
    container_name: wechatbot
    ports:
      - "13389:3389"
      - "10086:10086" 
      - "10087:10087" 
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    stdin_open: true
    tty: true
    volumes:
      - ./user_dat:/root/.wine/drive_c/users/root/AppData/Roaming/Tencent/WeChat
```
